### ISSUE TITLE
Run the updated code in the Android phone

### ISSUE THREAD

**Issue by PallayVenkatesh** [PallayVenkatesh/ASE_Project#7]
As this code won't run in the emulator, can you please run it in the real android mobile as soon as possible and update the issue

**Comment by PallayVenkatesh** [comment]
Please attach the screen shot in comments

**Comment by aggg6** [comment]
I have executed the code in my android mobile and I found that there is something wrong in loading the maps 
below is the screenshot of what I have observed when I run the code on my mobile
![image](https://cloud.githubusercontent.com/assets/25354179/23576926/5a08d418-0077-11e7-8f11-c248334b9073.png)

**Comment by PallayVenkatesh** [comment]
![screenshot_2017-03-05-23-09-44-088_com example application ase4](https://cloud.githubusercontent.com/assets/25230677/23597584/c952e95c-01f9-11e7-8e33-2c174ea65fb9.png)

**Comment by PallayVenkatesh** [comment]
I have checked it, its working now

**Comment by ROHITHKUMARN** [comment]
Location updation is working as expected; now getting destination coordinates and setting destination marker in the map activity is pending
